envoyproxy/xds-relay

- .gitignore
- internal/app/cache/cache.go
This change defines the cache interface for an in-memory cache that retains the DiscoveryResponses from the control plane and related watches/stream for a given aggregated key. The methods were defined based on the [sequence diagram](https://docs.google.com/document/d/1X9fFzqBZzrSmx2d0NkmjDW2tc8ysbLQS9LaRQRxdJZU/edit#heading=h.1g62tk7rs8tn) from the tech spec.
Issue: #9
> Initial cache interface

- internal/app/mapper/mapper.go
- internal/app/mapper/mapper_test.go
This PR implements the AnyMatch MatchPredicate and StringFragment Result.
Even though each test case has a single `TableEntry` its defined in a `var` so that more tests can be added without editing the test case itself in the subsequent PRs.
> Mapper.GetKey impl: any match to string result

- internal/app/mapper/mapper.go
- internal/app/mapper/mapper_test.go
DiscoveryRequest will always contain typeUrl
ADS will contain typeUrl https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/discovery.proto#L46
Implicit xds requests will have typeUrl set because go-control-plane mutates the DiscoveryRequest
ref: https://github.com/envoyproxy/go-control-plane/blob/master/pkg/server/server.go#L310
> remove typeUrl dependency in mapper

- Makefile
I shamelessly stole this idea of an auto-documented make from http://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
By running `make help` we get something like:
> Auto-documented makefile

- go.mod
- internal/app/server/server.go
- internal/pkg/log/log.go
- internal/pkg/log/zap.go
- internal/pkg/log/zap/zap.go
- internal/pkg/log/zap/zap_suite_test.go
- internal/pkg/log/zap/zap_test.go
- internal/pkg/log/zap_test.go
This adds a custom logging interface infront of the zap logger in order
to supply context and friendlier `With` structured logging, ex:
```
Log.Named("foo-component").With(
"field1", "value1",
"field2", "value2",
).Error("my error message")
```
Also decouples the 3rd party library code from slipping into other areas
of the application.
> Add logging interface

- Makefile
- integration/validator_tool_test.go
This PR removes the hack to list test files using `go list` in favor of the more idiomatic way of setting [build tags](https://golang.org/pkg/go/build/#hdr-Build_Constraints) to segment integration tests.
Build tags are opt-in, that's why they are useful for stuff like integration tests. This means that in order for tagged files to show up we have to specify the tags, so in this case we tag all integration tests as `integration` and specify that tag in the `integration-tests` make rule.
> Use tags to mark integration tests

- internal/app/cache/cache.go
Fixes #58 
The expiration time should only be delayed in SetResponse, since the intent of the TTL was to avoid stale responses in the cache. Adding/removing watches should not affect the expiration time of a key. This change removes that extension from AddWatch, and #59 already omits the expiry time extension.
> Don't extend TTL for AddWatch

- integration/upstream_client_test.go
Integration tests are flaky with the following output:
```
=== RUN   TestServerShutdownShouldCloseResponseChannel
2020/04/30 19:25:43 listen tcp :19000: bind: address already in use
FAIL	github.com/envoyproxy/xds-relay/integration	6.798s
FAIL
make: *** [integration-tests] Error 1
##[error]Process completed with exit code 2.
```
This is due to tests using the same port 19000: https://github.com/envoyproxy/xds-relay/blob/22fd938e737842b2236aa2c87fa550c9aff69016/integration/testdata/envoy_bootstrap.yaml#L7
https://github.com/envoyproxy/xds-relay/blob/2cbd631e7e86e3b51c2a837edb86da2ecb7d822f/integration/upstream_client_test.go#L31
> Change test port to avoid port conflict between tests

- internal/app/upstream/client.go
- internal/pkg/log/zap.go
Fix logging scope creep when chaining.
Issue: https://github.com/envoyproxy/xds-relay/issues/80
After fix:
```
{"level":"info","ts":1589236218.714848,"logger":"upstream_client","msg":"Initiating upstream connection","address":"127.0.0.1:18000"}
{"level":"info","ts":1589236218.715483,"msg":"Initializing server","address":"127.0.0.1:9991"}
^C{"level":"info","ts":1589236225.771179,"msg":"received interrupt signal:interrupt"}
{"level":"info","ts":1589236225.771255,"msg":"initiating grpc graceful stop"}
```
vs Prior:
```
{"level":"info","ts":1589236161.250703,"logger":"upstream_client","msg":"Initiating upstream connection","address":"127.0.0.1:18000"}
{"level":"info","ts":1589236161.251442,"logger":"upstream_client.orchestrator","msg":"Initializing …
```
> logger: Fix scope creep

- integration/e2e_test.go
- integration/logger.go
- internal/app/orchestrator/orchestrator.go
- internal/app/server/server_test.go
- internal/pkg/log/log.go
- internal/pkg/log/zap.go
Equivalent to `fmt.Sprintf`. Support templated logging. This is
especially important when passing the logger to go-control-plane in
certain packages, such as e2e tests.
Without this change we will continue to see log messages like the
following:
```
open watch +%v, %d, ...
```
Also
* Add debug and info logs to orchestrator
* Default to debug logs for e2e tests
> logger: Support formatted logging

- .github/workflows/integration-tests.yml
- integration/server_test.go
We retry the integration tests up to 3 times using https://github.com/marketplace/actions/retry-step.
This is a stopgap until we find out a better solution to solve issue described in https://github.com/envoyproxy/xds-relay/issues/84#issuecomment-628852414.
I'm adding the failing test just to confirm the retries actually happen.
> Retry integration tests up to 3 times

- internal/app/admin/http/handler.go
- internal/app/admin/http/handler_test.go
This change unmarshals xDS resources in the cache from the generic Any form based on the TypeURL, utilizing the same logic as https://github.com/envoyproxy/go-control-plane/blob/e933a9f2ccd2c350a7d7c67317fceb79b3cd8ff6/pkg/cache/v2/resource.go#L52. This change only unmarshals V2 resources. Resources whose type URLs do not match are included in the output under the `Unmarshalled` field. Addresses #93.
Example output:
```
{
"Resp": {
"VersionInfo": "1",
"Resources": {
"Endpoints": null,
"Clusters": null,
"Routes": null,
"Listeners": [
{
"name": "lds resource"
}
],
"Secrets": null,
"Runtimes": null,
"Unmarshalled": null
},
"Canary": false,
"TypeURL": "type.googleapis.com/envoy.api.v2.Listener",
"Nonce": "",
"ControlPlane": null
},
"Requests": [
{
"type_url": …
```
> Unmarshal v2 resources in cache_dump

- internal/pkg/log/zap.go
This change puts xdsrelay-specific fields under one key `json`. We can later make this value configurable or optional.
example log:
`{"level":"debug","ts":1594750385.907022,"logger":"upstream_client","msg":"received message","json":{"response_version":"v0","response_type":"type.googleapis.com/envoy.api.v2.Cluster","resource_length":2}}`
> Add json namespace for service fields

- api/protos/bootstrap/v1/bootstrap.proto
- pkg/api/bootstrap/v1/bootstrap.pb.go
We actually set the default log output to STDERR here:
https://github.com/envoyproxy/xds-relay/blob/master/internal/app/server/server.go#L54-L56
This is also consistent with the zap default: https://godoc.org/sigs.k8s.io/controller-runtime/pkg/log/zap#WriteTo.
> Fix comment on default log output

- internal/app/orchestrator/orchestrator_test.go
Assert stats only after watches have been cleaned up. This prevents a
flaky case where we check that the stat has been incremented before
the codepath is executed.
> Fix flaky unit test

- internal/app/metrics/metrics.go
- internal/app/upstream/client.go
- internal/app/upstream/error_interceptor.go
This PR adds a [`StreamClientInterceptor`](https://github.com/grpc/grpc-go/tree/master/examples/features/interceptor#stream-interceptor) that records whenever there's an error in either `SendMsg` or `RecvMsg` functions in any of the calls in the bidi streams present in the upstream client.
> Add Error Interceptor

- internal/app/upstream/error_interceptor.go
Currently the error message can't be viewed from the logs, so adding it as a field.
> Add error message to error interceptor logging

- internal/app/metrics/metrics.go
- internal/app/orchestrator/downstream.go
- internal/app/orchestrator/downstream_test.go
- internal/app/orchestrator/orchestrator.go
Although the language specification for Go specifies that channels will
be garbage collected when no longer referenced, the receiver (
go-control-plane in this scenario) may be still looking for an explicit
signal. In our experiments, we saw that there were scenarios where cache
TTL triggering removal of downstream watchers, did not cause the Envoy
clients to resend requests.
> Explicitly close downstream watches

- internal/app/cache/cache_test.go
- internal/app/metrics/metrics.go
- internal/app/orchestrator/orchestrator_test.go
- internal/app/server/server.go
- internal/pkg/stats/stats.go
- internal/pkg/stats/statsd_point_tags_reporter.go
- internal/pkg/stats/statsd_point_tags_reporter_test.go
This PR adds a statsd reporter with support for point tags using the format used by Lyft. Follow up PRs could extend this approach to generalize the creation of point tags, but I opted for the simplest-yet-extensible solution for now.
In this PR we convert the metrics that contained the aggregated key in the metric name to use the new format where the aggregated key becomes a point tag.
> Statsd Point Tags Reporter

- internal/app/admin/http/handler.go
- internal/app/admin/http/handler_test.go
- internal/app/server/server_test.go
- internal/pkg/log/log.go
- internal/pkg/log/zap.go
This change:
- Supports returning the current log level in string format when no parameter is supplied to the admin logging endpoint.
- Handles trailing slashes in URLs, such that paths with and without are registered to the same handlers without any redirects. [The redirects are a characteristic of http handlers in Go](https://golang.org/pkg/net/http/#ServeMux):
```If a subtree has been registered and a request is received naming the subtree root without its trailing slash, ServeMux redirects that request to the subtree root (adding the trailing slash). This behavior can be overridden with a separate registration for the path without the trailing slash. For example, registering "/images/" causes ServeMux to redirect a request for "/images" to "/images/", unless "/images" has been …
```
> Remove redirect behavior for admin endpoints and support getting log level

- go.mod
- integration/upstream_client_test.go
- internal/app/admin/http/handler.go
- internal/app/admin/http/handler_test.go
- internal/app/cache/cache.go
- internal/app/cache/cache_test.go
- internal/app/mapper/mapper.go
- internal/app/mapper/mapper_test.go
- internal/app/orchestrator/downstream.go
- internal/app/orchestrator/downstream_test.go
- internal/app/orchestrator/orchestrator.go
- internal/app/orchestrator/orchestrator_test.go
- internal/app/orchestrator/upstream.go
- internal/app/transport/request.go
- internal/app/transport/response.go
- internal/app/transport/watch.go
- internal/app/transport/watch_test.go
- internal/app/upstream/client.go
- internal/app/upstream/client_test.go
As an initial step to introduce v3 api, we need to separate the logic of orchestrator such that there are no dependencies on v2/v3 DiscoveryRequest.
This PR removes the dependency on the response channels and creates a watch interface to send responses.
Next PR: abstract DiscoveryRequest from orchestrator and mapper.
> Add Request/Response abstraction

- integration/upstream_client_test.go
- internal/app/transport/request.go
- internal/app/transport/response.go
- internal/app/transport/stream.go
- internal/app/transport/watch_test.go
- internal/app/upstream/client.go
- internal/app/upstream/client_test.go
The stream send and recv depended on the V2 references. Abstracting stream such that the upstream/client.go does not depend on V2 protos.
> Abstract stream

- internal/app/mapper/mapper_test.go
As mentioned in https://github.com/envoyproxy/xds-relay/pull/137#discussion_r487331506, these tests were removed by mistake with the exception of the last one, `non matching field type`, since by construction we cannot have an invalid field type. This PR adds them back.
> Add tests back

- internal/app/metrics/metrics.go
- internal/app/orchestrator/orchestrator.go
- internal/app/orchestrator/orchestrator_test.go
Log error and close the watch.
For longer term, there is an open issue to support unaggregated keys.
> Add stopgap for unaggregated keys

- internal/app/orchestrator/orchestrator.go
- internal/app/orchestrator/orchestrator_test.go
- internal/app/transport/streamv2.go
- internal/app/transport/streamv3.go
- internal/app/upstream/client.go
When upstream control plane rotates, the grpc client has to make a new connection. Today we recognize an issue in the stream and dont retry. We should at least close the downstream sidecar streams, so that we get some semblance of retry from envoy sidecars. This could cause thundering herd, but this is a stopgap until the next PR fixes the retry.
> Evict cache on upstream failure

- internal/app/server/server.go
- internal/app/server/server_test.go
Resolving Issue https://github.com/envoyproxy/xds-relay/issues/118
To keep server from hanging after sending SIGINT/SIGTERM, cancel global context before calling gracefulStop()
> Shutdown bug

- README.md
- example/config-files/envoy-bootstrap-1.yaml
- example/config-files/envoy-bootstrap-2.yaml
- example/main.go
* to use getenvoy to install the binary instead of running it via `getenvoy run`. On Mac, there is process exiting issues following the standard:1.11.1 instructions.
* clarify dir where example configurations are located.
* clearer naming for envoy client node IDs and clusters
* update jq queries to reflect .Cache[0] parent (currently broken)
> Update example in README

- integration/upstream_client_test.go
- internal/app/admin/http/handler_test.go
- internal/app/metrics/metrics.go
- internal/app/orchestrator/orchestrator.go
- internal/app/orchestrator/orchestrator_test.go
- internal/app/upstream/client.go
- internal/app/upstream/client_mock.go
- internal/app/upstream/client_test.go
- internal/app/upstream/stream_mockv2.go
- internal/app/upstream/stream_mockv3.go
This PR proposes the following change in behavior:
- Any stream errors in send and recv are retried by the client.
- Any stream creation errors are retried by client
- A malformed/unsupported typeurl causes the response channel to be closed and orchestrator will close the downstream watches. We earlier did the work for the orchestrator to close the watches when response channel is closed. This is not expected to cause any thundering herd issue.
- The retry eventually succeeds or keeps incrementing a stat. We can add alarms around the stat.
- TTL expiry can still cancel the top level context and the retry stops. The cancel flow has been demonstrated in the integration tests.
Grpc concepts on which the impl relies:
1. grpc takes care of connection management. Once the connection is …
> Retry upstream stream failures

- go.mod
- go.sum
- internal/app/upstream/client.go
- internal/app/upstream/client_test.go
- internal/app/upstream/stream_mockv2.go
- internal/app/upstream/stream_mockv3.go
While deploying to staging we realized that in case of stream retries, the xdsrelay pods were getting oomkilled.
The OOM was happening due to goroutine leak in the upstream client.
In order to fix it, we used `go.uber.org/goleak` ([doc](https://github.com/uber-go/goleak)) in the test cases, and fixed the leaks using test cases. The resulting code does not OOM kill anymore. 
> fix oomkilled

- internal/app/metrics/metrics.go
- internal/app/orchestrator/orchestrator.go
- internal/app/orchestrator/orchestrator_test.go
Signed-off-by: Samra Belachew <sbelachew@lyft.com>
Added a couple of logs and a stat to NACK behavior in CreateWatch() to test out behavior of NACK requests. Stat will count number of NACK watches created per aggregated key. Logs provide detail on NACK request itself, whether it leads to a returned cached response, and if it opens up a new stream.
> NACK logs + stat

- internal/app/upstream/client_test.go
In the upstream client tests, the `defer` way of closing goroutines was turning out to be flakey. By the time the go-leak ran the goroutines were not always done.
Instead we have to explicitly wait for each test cleanup before the go-leak ran. In go tests there is no way to add a per test teardown hook.
Verfied each test with `-count=100`
> Fix flakey tests

- internal/app/orchestrator/orchestrator.go
- internal/app/orchestrator/orchestrator_test.go
- internal/app/transport/streamv2.go
- internal/app/transport/streamv3.go
- internal/app/upstream/client_test.go
The PR handles 2 scenarios:
1. A nack request can cause endless to-fro between a sidecar and xdsrelay. In case of NACK the version never updates. so the sidecar's version will never match the cache's version, causing immediate response from cache. The immediate response should only be sent when the request is not a nack. When the request is a nack, the watch should hold until a further update is received from upstream.
2. xdsrelay upstream client always caches the first request and uses it for the further upstream requests until cache is evicted. In case the first request was a nack(can happen when xdsrelay server instance just started up), we still need to update the cache, but should not send the ErrorDetails. Most upstream control planes hold the watch on nack request(verified with …
> Handle NACK

- integration/upstream_client_test.go
- internal/app/metrics/metrics.go
- internal/app/orchestrator/orchestrator.go
- internal/app/orchestrator/orchestrator_test.go
- internal/app/upstream/client.go
- internal/app/upstream/client_test.go
While rolling out xdsrelay in staging, we noticed difficulty in debugging a cache drift between upstream control plane and xdsrelay.
It was hard to associate errors in xdsrelay with the per service cache drift. It would be easy to track errors if we had granular per key stats.
> Add more client stats/logs per aggregated key

- internal/app/orchestrator/downstream.go
- internal/app/orchestrator/downstream_test.go
- internal/app/orchestrator/orchestrator.go
- internal/app/orchestrator/orchestrator_test.go
- internal/app/transport/watch.go
- internal/app/transport/watch_test.go
- internal/app/transport/watchv2.go
- internal/app/transport/watchv3.go
While rolling xdsrelay for. t1 services, we discovered that there are some edge cases during which send happens on closed channel.
```
  | Nov 5, 2020 @ 11:16:55.595 | child exited
  | Nov 5, 2020 @ 11:16:55.595 | panic stacktrace
  | Nov 5, 2020 @ 11:16:55.595 | child process exited with error
  | Nov 5, 2020 @ 11:16:55.595 | error waiting for child process to exit
  | Nov 5, 2020 @ 11:16:55.595 | wrap exited
  | Nov 5, 2020 @ 11:16:55.592 | ignoring signal: SIGCHLD
  | Nov 5, 2020 @ 11:16:55.576 | -
  | Nov 5, 2020 @ 11:16:55.576 | /code/xds-relay-private/xds-relay/internal/app/transport/watchv3.go:34 +0xd3
  | Nov 5, 2020 @ 11:16:55.576 | github.com/envoyproxy/xds-relay/internal/app/transport.(*watchV3).Send(0xc003e9c7a8, 0x1034080, 0xc0023f5e80, 0x1034080)
  | Nov 5, 2020 @ …
```
> Handle panic

- internal/app/admin/http/handler.go
- internal/app/admin/http/ready.go
- internal/app/admin/http/ready_test.go
While rolling out in staging we realized that there are sometimes cx issues due to which there is cache mismatch between upstream and xdsrelay. Due to the severity of traffic we end up terminating the erroneous pod. We need a way to web off faulty pods to continue investigating the issue.
> Add ready endpoint

- internal/app/admin/http/cache.go
- internal/app/admin/http/cache_test.go
- internal/app/admin/http/handler.go
- internal/app/admin/http/handler_test.go
- internal/app/orchestrator/orchestrator.go
- internal/app/orchestrator/orchestrator_test.go
- internal/app/server/server.go
- internal/app/upstream/client.go
- internal/app/upstream/client_mock.go
- internal/app/upstream/client_test.go
- pkg/marshallable/cache.go
This reverts commit 1606087f0eb35a779f4925e75763084bbae92812.
The approach is not good since its causing concurrent access to map
> Revert "Add endpoint to check stream status (#192)"

- internal/app/mapper/mapper.go
- internal/app/mapper/mapper_test.go
In our heterogeneous fleet, there could be nodes which do not match the nodemetadata. In such cases, the match from those nodes fail. This PR makes changes to ensure that the requests from such nodes do not fail and fallback to other rules.
> Make NodeMetadataMatch tolerant to empty struct values

- internal/app/metrics/metrics.go
- internal/app/orchestrator/downstream.go
- internal/app/orchestrator/downstream_test.go
- internal/app/orchestrator/orchestrator.go
- internal/app/orchestrator/orchestrator_test.go
- internal/app/transport/request.go
- internal/app/transport/request_test.go
- internal/app/transport/requestv2.go
- internal/app/transport/requestv3.go
- internal/app/transport/watch.go
- internal/app/transport/watch_test.go
- internal/app/transport/watchv2.go
- internal/app/transport/watchv3.go
When sending the response to clients, drop the older response currently
in the transport queue, so that we always send the latest response.
Also,
* Add stats scope to watch / transport layer
* Return nil in unaggregated key scenario
> Dequeue stale responses

- internal/app/admin/http/cache.go
- internal/app/admin/http/cache_test.go
- internal/app/admin/http/handler.go
- internal/app/admin/http/handler_test.go
Clear cache handler should have a path consisting of 4 entries (`address/cache/clear/x`). This change has it parse its own parameter instead of relying on `getParam()`
Signed-off-by: Samra Belachew <sbelachew@lyft.com>
> Clear Cache Endpoint Params

- example/config-files/aggregation-rules.yaml
- example/config-files/envoy-bootstrap-1.yaml
- example/config-files/envoy-bootstrap-2.yaml
- example/main.go
- go.sum
This patch migrates example-management-server to v3 xDS apis.
v2 xDS apis are deprecated and removed form Envoy in Q1 2021.
Signed-off-by: Kenjiro Nakayama <nakayamakenjiro@gmail.com>
> Migrate example-management-server to v3 xDS APIs

- README.md
This patch fixes to:
- add `--base-id {0,1}` option to run multiple envoys on the same host.
- replaces `cache/cluster1_cds` with `cache/staging_cds`. It was updated by cd675d4.
> Fix cache key in README

- internal/app/server/server.go
This patch make a tiny change which fixes a log format.
BFORE:
```
{"level":"info","ts":1609729155.4176533,"msg":"received interrupt signal:%!(EXTRA string=interrupt)","json":{}}
```
AFTER:
```
{"level":"info","ts":1609806458.4018972,"msg":"received interrupt signal","json":{"signal":"interrupt"}}
```
Signed-off-by: Kenjiro Nakayama <nakayamakenjiro@gmail.com>
> Fix log format

- internal/app/upstream/client.go
The warning message is always printed when keep alive time is unset.
The current `example` config also causes validation error as:
```
$ ./bin/xds-relay  -m validate --aggregation-rules example/config-files/aggregation-rules.yaml -c example/config-files/xds-relay-bootstrap.yaml
{"level":"info","ts":1609554826.4375143,"logger":"upstream_client","msg":"Initiating upstream connection","json":{"address":"0.0.0.0:18000"}}
{"level":"warn","ts":1609554826.4375317,"msg":"Keepalive time parsing failed%!(EXTRA string=time: invalid duration \"\")","json":{},"stacktrace":"github.com/envoyproxy/xds-relay/internal/pkg/log.(*logger).Warn\n\t/home/knakayam/dev/xds-relay/internal/pkg/log/zap.go:95\ngithub.com/envoyproxy/xds-relay/internal/app/upstream.getKeepaliveParams\n\t/home/knakayam/dev/xds-relay/inte …
```
> Do not print warn message when keep alive time is unset

- internal/app/orchestrator/orchestrator.go
- internal/app/upstream/client.go
There are two error scenarios currently that leads to cache drifts
between the management server and xds-relay.
1. There is a bug where the stream is stuck indefinitely if the send chan
is closed unexpectedly. The recv routine stays open and the waitgroup
never completes, blocking retries.
2. If the response receiver channel for `recv()` is blocked, the upstream
client is blocked from sending ACKs back to the management server.
> upstream client: Handle recv() blocked scenarios
