CODE_OF_CONDUCT.md
CONTRIBUTING.md
DCO
OWNERS.md
README.md
STYLE.md

Most of these are lightly modified versions of the same files from
[envoy](github.com/envoyproxy/envoy).
Add:
* Code of Conduct
* DCO
* Owners
* Cursory Style Guide
* High level contributing document

Add initial contribution guidelines

---

internal/app/server/server.go
internal/pkg/log/log.go
internal/pkg/log/log_suite_test.go
internal/pkg/log/log_test.go
main.go

[Related](https://github.com/envoyproxy/xds-relay/pull/11#discussion_r384912980)

Remove license headers from .go files

---

internal/app/mapper/mapper.go
internal/app/mapper/mapper_test.go

This PR adds the [RequestTypeMatch](https://github.com/envoyproxy/xds-relay/blob/master/api/protos/aggregation/v1/aggregation.proto#L50-L54) predicate

RequestTypeMatch predicate

---

internal/app/mapper/mapper.go
internal/app/mapper/mapper_test.go

This PR adds the [RequestNodeMatch](https://github.com/envoyproxy/xds-relay/blob/master/api/protos/aggregation/v1/aggregation.proto#L57-L74) predicate

RequestNodeMatch predicate

---

internal/app/mapper/mapper.go
internal/app/mapper/mapper_test.go

Adding the [And and Or](https://github.com/envoyproxy/xds-relay/blob/master/api/protos/aggregation/v1/aggregation.proto#L88-L92) predicates

And and Or predicates

---

internal/app/mapper/mapper.go
internal/app/mapper/mapper_test.go

This implements [not_match](https://github.com/envoyproxy/xds-relay/blob/master/api/protos/aggregation/v1/aggregation.proto#L96) predicate

NotMatch predicate

---

internal/app/mapper/mapper.go
internal/app/mapper/mapper_test.go

This PR implements the result [RequestNodeFragment](https://github.com/envoyproxy/xds-relay/blob/master/api/protos/aggregation/v1/aggregation.proto#L143)

RequestNodeFragment result

---

internal/app/cache/cache.go
internal/app/cache/cache_test.go

The cache currently stores the raw discovery response. Store alongside
it the marshaled resource so that we don't have to re-serialize on every
downstream fan out.

Cache the serialized response

---

internal/app/cache/cache.go
internal/app/orchestrator/orchestrator.go
internal/app/orchestrator/orchestrator_test.go
internal/app/server/server.go

Add orchestrator interface

---

internal/app/cache/cache.go

This PR is an attempt to make sharing of the cache resources more efficient amongst different go-routines.

More precise locking for cache.Fetch

---

internal/app/cache/cache.go
internal/app/cache/cache_test.go

* Return `Resource` rather than `Response` on fetch. Orchestrator needs
the Resource object afterall in order to identify and notify watches.
* Export `Resource` and `Response` members that will be used by calling
classes.
* Change the marshaled resource type to `[][]byte`, which is what
go-control-plane expects when constructing the Response.
* Remove the comment about notify watches, responsibility has moved to
Orchestrator.

Return Resource on cache Fetch

---

OWNERS.md

Add maintainers

---

go.mod
go.sum
internal/app/admin/http/handler.go
internal/app/admin/http/handler_test.go
internal/app/cache/cache.go
internal/app/cache/cache_test.go
internal/app/orchestrator/downstream.go
internal/app/orchestrator/orchestrator.go
internal/app/orchestrator/orchestrator_test.go

Context is in this issue: https://github.com/envoyproxy/go-control-plane/issues/299.

Use go-control-plane's PassthroughResponse

---

integration/e2e_test.go
integration/testdata/bootstrap_configuration_complete_tech_spec.yaml
integration/testdata/bootstrap_configuration_e2e.yaml
integration/testdata/bootstrap_configuration_invalid_hostname_value.yaml
integration/testdata/bootstrap_configuration_invalid_log_level.yaml
integration/testdata/bootstrap_configuration_invalid_port_value.yaml
integration/testdata/bootstrap_configuration_invalid_statsd_port.yaml
integration/testdata/bootstrap_configuration_missing_address.yaml
integration/testdata/bootstrap_configuration_missing_flush_interval.yaml
integration/testdata/bootstrap_configuration_missing_root_prefix.yaml
integration/testdata/bootstrap_configuration_missing_statsd_address.yaml
integration/testdata/bootstrap_configuration_negative_cache_ttl.yaml
integration/upstream_client_test.go
internal/app/cache/cache_test.go
internal/app/orchestrator/orchestrator_mock.go
internal/app/orchestrator/orchestrator_test.go
internal/app/server/server.go
internal/app/upstream/client_mock.go
internal/pkg/log/log_mock.go
internal/pkg/log/zap.go
internal/pkg/log/zap_test.go

Add option to log to filesink

---

integration/upstream_client_test.go
internal/app/cache/cache.go
internal/app/cache/cache_test.go
internal/app/mapper/mapper.go
internal/app/mapper/mapper_mock.go
internal/app/mapper/mapper_test.go
internal/app/metrics/metrics.go
internal/app/orchestrator/downstream.go
internal/app/orchestrator/orchestrator.go
internal/app/orchestrator/orchestrator_mock.go
internal/app/orchestrator/orchestrator_test.go
internal/app/server/server.go
internal/app/upstream/client.go
internal/app/upstream/client_mock.go
internal/app/upstream/client_test.go
internal/pkg/stats/stats_mock.go

Add stats to:
* orchestrator
* mapper
* cache
* upstream

Add stats to main workflows

---

integration/e2e_test.go
internal/app/cache/cache.go
internal/app/orchestrator/orchestrator.go
internal/app/server/server.go
internal/app/upstream/client.go

This change unifies some of the overlapping logging keys and makes them all snake_case (which I am not wedded to).

Standardize logging fields

---

internal/app/admin/http/handler.go
internal/app/admin/http/handler_test.go
internal/app/orchestrator/downstream.go
internal/app/orchestrator/orchestrator.go
internal/app/orchestrator/orchestrator_test.go
internal/app/upstream/client_mock.go
internal/app/upstream/client_test.go

Adds support for outputting the entirety of the cache via admin API.

Full cache dump support for admin API

---

internal/app/orchestrator/orchestrator.go

Log request on aggregated key map failure

---

internal/app/orchestrator/orchestrator.go

This PR fixes the conversion of the TTL from `durationpb.Duration` to `time.Duration`. This is the cause of the expiration times in the cache being set to `0001-01-01 00:00:00 +0000 UTC` (which ended up causing keys to never expire).

Fix conversion of TTL to time.Duration

---

go.mod
go.sum
integration/e2e_test.go
internal/app/admin/http/cache_test.go
internal/app/admin/http/handler_test.go
internal/app/mapper/mapper_test.go
internal/app/orchestrator/orchestrator_test.go
internal/app/orchestrator/v2.go
internal/app/orchestrator/v3.go
internal/app/transport/watch_test.go
internal/app/transport/watchv2.go
internal/app/transport/watchv3.go
internal/pkg/util/stringify/stringify_test.go

go-control-plane had not been updated in 4 months and quite a few api changes have been pushed in gcp since.
In order to keep the change surface smaller i'll try to bring in updates in batches

Update gcp until 08/12

---

internal/app/upstream/client.go

Add more logs

---

internal/app/metrics/metrics.go
internal/app/orchestrator/orchestrator.go

Add stats for fanout latency

---

internal/app/cache/cache.go
internal/app/orchestrator/orchestrator.go
internal/app/upstream/client.go

Signed-off-by: Samra Belachew <sbelachew@lyft.com>
Updated log messages, added some version arg when missing, and created two new logs around `ctx.Done()`

Debug Logs

---

internal/app/orchestrator/orchestrator.go

Log resource names during CreateWatch()

---

.github/workflows/api.yml
.github/workflows/common.yml
.github/workflows/end2end-tests.yml
.github/workflows/integration-tests.yml
example/main.go
integration/upstream_client_test.go
internal/app/upstream/client.go
internal/pkg/util/duration_test.go

CI: Fix workflows from master -> main branch rename
